### ISSUE TITLE
Invalid phone number results in uncaught exception for SMS

### ISSUE THREAD

**Issue by jdrummey** [tableau/VizAlerts#103]
This issue was found in the original SMS code that was used for PATH, it might not be an issue today.

When there's a phone number that isn't recognized by Twilio (in this case it was a phone number that was missing a digit) then Twilio throws a "phone number doesn't exist" error which the SMS code catches, however the exception is not properly carried up the chain so the failure email that goes out has something like "uncaught exception "e"".

I've looked at the v2.0 code and I can't tell if it would deal with this or not, we'll need to test for it. The test case would be to use a known good number and then remove a single digit.

Jonathan

**Comment by mcoles** [comment]
I tested this a second ago with a number with a bad character, and with a non-numeric character. Seems to be caught just fine:

![image](https://user-images.githubusercontent.com/14928335/28985882-7e585468-7919-11e7-9d51-5bfc8e4da514.png)


Let me know if you're still able to reproduce this in 2.1.0 as you test it! But it looks fixed to me.

**Comment by mcoles** [comment]
Assumed fixed.
