### ISSUE TITLE
Appendix A wrong in install_guide for optional packages

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#109]
The fact that phonenumberslite and twilio are required, not optional, was missed in the appendix.

**Comment by smenago** [comment]
When installing twilio I am recieving the following error -
Command python setup.py egg_info failed with error code 1 in c:\users\admini~1\appdata
local\temp\pip_build_administrator\cffi
Storing debug log for failure in C:\Users\administrator\pip.pip.log.

On the stackoverflow and python.org I see that I should do a rollback and then upgrade the python version, but accoring to the install_guide I need a specific version.  Is there any info. available to correct the error?  

When I execute the test I receive the following -
C:\VizAlerts>C:\Python27\python C:\VizAlerts\vizalerts.py
Traceback (most recent call last):
  File "C:\VizAlerts\vizalerts.py", line 28, in <module>
    from vizalert import emailaction
  File "C:\VizAlerts\vizalert\emailaction.py", line 29, in <module>
    import vizalert
  File "C:\VizAlerts\vizalert\vizalert.py", line 21, in <module>
    import smsaction
  File "C:\VizAlerts\vizalert\smsaction.py", line 7, in <module>
    import twilio
ImportError: No module named twilio
