### ISSUE TITLE
Support additional formats for embedded content in alert emails (csv, pdf)

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#11]
Advanced Alerts allows the embedding of a Tableau Server View, rendered as a PNG image, in the emails that are sent via the VIZ_IMAGE() placeholder text. Users have requested that CSV and PDF formats be embeddable into the emails as well. This would need to be done after [Allow embedding of customized View content in Advanced Alerts](https://github.com/tableau/VizAlerts/issues/6), for the CSV side of things.

Thereafter, there could be three placeholder text values for these three content types:

VIZ_IMAGE()
VIZ_CSV()
VIZ_PDF()

In thinking about this feature, this set of faux-functions *could* also be used to customize Simple Alerts as well, simply by adding them to the level of detail in the view data. In that case, they would toggle the addition of the content to the Simple Alert email. If present, the content of that type would be embedded in / attached to the email. If left out, nothing would be sent except the email subject, a blank body, and the standard footer.

By default, Simple Alerts always send the rendered viz image and attach the CSV of the view data. I don't think we'd want to change that. So within a Simple Alert, it seems like they should work like this:

Function | Value | Result
------------ | -------------  | ------------- 
VIZ_IMAGE() | (field missing) | View image is embedded
VIZ_IMAGE() | null | View image is embedded
VIZ_IMAGE() | 1 | View image is embedded
VIZ_IMAGE() | 0 | View image is **not** embedded
VIZ_CSV() | (field missing) | View CSV is embedded
VIZ_CSV() | null  | View CSV is embedded
VIZ_CSV() | 1 | View CSV is embedded
VIZ_CSV() | 0 | View CSV is **not** embedded
VIZ_PDF() | (field missing) | View PDF is **not** embedded
VIZ_PDF() | null  | View PDF is embedded
VIZ_PDF() | 1 | View PDF is embedded
VIZ_PDF() | 0 | View PDF is **not** embedded

In the case of multiple values that disagree, the most restrictive values found would trump others--in other words, having the field being included in the view with a value of "0" would trump another value found of "1" or anything else.

For Advanced Alerts, all of these should be able to accept valid paths to Tableau Server *views*, with customizable URL parameters as described [here](https://github.com/tableau/VizAlerts/issues/6). See comments at that link for why we would not do this for Simple Alerts.

**Comment by jdrummey** [comment]
This idea has now been implemented so this can be closed out.

**Comment by mcoles** [comment]
A million thank-you's, JDrum! Closing this issue.
