### ISSUE TITLE
Install_guide and user_guide should be moved out of .docx format

### ISSUE THREAD

**Issue by stevenqzhang** [tableau/VizAlerts#110]
You probably have good reasons why these two documents are in docx form (maybe this is what Tableau Server admins generally prefer), but it would be nice to have these two documents in markdown or RST instead:

1. you can't see diffs of docx files checked into version control
2. One day Tableau Server linux will be released, and linux admins probably won't want to open docx files
3. You can't view the documentation in the web browser. It's a barrier to reading documentation, at least for me

**Comment by mcoles** [comment]
Nope, no good reasons other than the ability to embed images and for portability of a sort. We actually have an Issue for this actually, but we didn't have any clear idea of what format would be best:

https://github.com/tableau/VizAlerts/issues/79

**Comment by stevenqzhang** [comment]
Ah okay. Markdown's probably the best option for, and we can always easily convert to other options. Feel free to close as dupe on this issue
