### ISSUE TITLE
Relax field name requirements for Advanced Alerts

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#12]
As of today, VizAlerts looks for specific field names in the data exported from a View to tell it what the properties of the email it's trying to send should be. They need to be exact matches to map correctly. The current field names are:

" Email To *"
" Email From ~"
" Email CC ~"
" Email BCC ~"
" Email Subject *"
" Email Header ~"
" Email Body *"
" Email Footer ~"
" Email Action *"
" Email Consolidate ~"
" Email Footer ~"

This strict requirement creates a few problems for usability:

1. The preceding spaces are easy to miss if fields are created manually, and can sometimes get erased by certain tools that auto-trim them. This causes them not to be recognized, and cause unintended behavior.

2. Field names must be unique within a single data connection in Tableau, so if you wanted to build two different alerts with different content in them, but which are based on the same data connection, you can't really do it right now. The workaround is to duplicate the connection entirely, which allows you to customize the field values for the new alert but keep the original logic in the old alert. That's pretty awkward to perform, duplicates work should the data connection logic need to change in the future, and can inflate workbook size.

For those reasons and probably more, VizAlerts should switch from an exact-match requirement to a pattern-match requirement on the field names, while retaining backward-compatibility with the old style. I imagine it would be something like a regex:

"\s{0,1}Email\sTo\s\*.*"

...which, translated, is intended to mean "a single space or no space, then "Email", then a single space, then "To", then a space, then an asterisk, then anything else you want to tack on the end".

That should be sufficiently strict to ensure that these special fields never conflict with any normal field names someone would use in their data connection, but also allow enough flexibility that they can create new ones for other alerts using the same datasource.

New logic will need to be added to VizAlerts that will check for "duplicate" fields in the data based on searches in this pattern, and handle the error appropriately if found.

**Comment by AirCooledNut** [comment]
I ran into this very exact issue Wednesday!  I ended up splitting my report in two, one for alerts when a workbook has not been read in a certain amount of time, one for alerts when 7 business days past the unread period have passed and the workbook can be deleted.  Good timing, hope this endeavor works!

**Comment by mcoles** [comment]
This one is driving me nuts. I had to separate my Extract Alert workbook into two whole separate workbooks as a result (though in fairness it was partly because I was using a parameter that I had to change). I'd try and implement a change soon but another contributor is looking at restructuring code in a fairly large way, so I'm going to hold off just yet.

**Comment by mcoles** [comment]
This will be implemented in v2.0.
