### ISSUE TITLE
HTTP 500 Error generating PDF from content reference 

### ISSUE THREAD

**Issue by rishabh1991** [tableau/VizAlerts#127]
Hi,

I am facing the issue with viz alert. Below is the log and error code
The following errors were encountered trying to process your alert:

General errors:
Unable to render content reference VIZ_PDF(workbook/veiw) with error:
HTTP error getting vizdata from url 
Code: 500 Reason: Internal Server Error
Unable to process alert Trigger2 as csv, error: Alert was triggered, but encountered a failure getting data/image references:
Unable to render content reference VIZ_PDF(workbook/veiw) with error:
HTTP error getting vizdata from url 

Code: 500 Reason: Internal Server Error
This error is intermittent. Can you please help.

Thanks
Rishabh

**Comment by mcoles** [comment]
Hi Rishabh. You've already opened a discussion on our forum about this, which is where we prefer to handle all our support requests. Let's continue the troubleshooting process there.

https://community.tableau.com/thread/250785
