### ISSUE TITLE
Anaplan and SAP BO to Tableau connection

### ISSUE THREAD

**Issue by natashasweety7** [tableau/VizAlerts#128]
we are using Anaplan to view my data in tables. Is it possible to get the data from Anaplan dashboards and visualize them in [Tableau](https://mindmajix.com/tableau-advanced-training)?

Same applies for SAP BO reports.
Thanks in advance.

**Comment by mcoles** [comment]
Hi @natashasweety7. This is not the right place to ask. I would recommend starting here: https://www.tableau.com/about/blog/2016/10/connect-directly-your-anaplan-data-tableau-61853
