### ISSUE TITLE
PDF Merge feature does not respect Sort Order field

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#132]
https://community.tableau.com/thread/258703

Doesn't look like we're respecting the Sort Order field when we have a Consolidate Lines setting in play when it comes to merging multiple PDFs in to a single attachment. I don't think we built the merging code with the sorting field in mind--or if we did, it's not working properly right now. It _does_ work to specify the PDFs you want merged into a single Email Attachment line, in the order you want them merged in, e.g.:

VIZ_PDF(DailySales/Page1|filename=SalesReport|mergepdf) VIZ_PDF(DailySales/Page2|filename=SalesReport|mergepdf)

... etc.

**Comment by jdrummey** [comment]
My memory is that when I first wrote the code it did use the sort field, but it's changed a bit since then. :)

**Comment by mcoles** [comment]
Closing as I believe this is duplicative of #141. Keeping that because it describes the problem more clearly.

**Comment by mcoles** [comment]
Added a doc update in #143 to help a little with this, hopefully
