### ISSUE TITLE
Ad-hoc extract refreshes do not trigger VizAlerts on the "On refresh success/failure" schedules

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#138]
Had some users who trigger extract refreshes via a script, rather than on a schedule, whose VizAlerts were not firing when the refreshes completed. This required a workaround in the CustomSQL for the VizAlertsConfig workbook.

https://community.tableau.com/message/786006#786006

This should be an easy fix we can just drop into the next version.

**Comment by AirCooledNut** [comment]
If it’s an easy SQL change can you provide the necessary code so we can do it ourselves?

Thank you,
    Toby Erkson
    Tableau Administrator & Programmer/Analyst
    Desk: 503-745-7604
    Daimler Trucks North America LLC, Montgomery Park, Portland, Oregon

**Comment by mcoles** [comment]
It was attached on the thread, but here it is again just because.

[VizAlertsConfig.sql.txt](https://github.com/tableau/VizAlerts/files/2160081/VizAlertsConfig.sql.txt)

**Comment by mcoles** [comment]
Note that I haven't fully tested that code yet. Should work fine, but YMMV.

**Comment by mcoles** [comment]
Fixed in #143
