### ISSUE TITLE
Update documentation for TSM commands

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#139]
Need to update the "tabadmin" commands with parallel "TSM" commands.

https://community.tableau.com/message/810689

**Comment by marineson09** [comment]
Just wondering why this was closed? IF the documentation was updated, are you able to point me/us in the right direction? Or make it apparent in the docs? 👍 :)

**Comment by mcoles** [comment]
Yes, sorry, I got a little close-happy and closed a bunch of issues before committing. Fixed in #143
