### ISSUE TITLE
Image rendering Issue

### ISSUE THREAD

**Issue by Ram09111** [tableau/VizAlerts#140]
Unable to render content reference VIZ_IMAGE(ABCD/Data) with error:
HTTP error getting vizdata from url https://tesiting.com/views/ABCD/Data?&:format=png&:size=1500,1500&:refresh=y. Code: 404 Reason: Not Found

URL must be https://tesiting.com/#/views/ABCD/Data

Missing # i am unable to generate image.

**Comment by mcoles** [comment]
Please reach out for support at https://community.tableau.com/vizalerts. Thanks!
