### ISSUE TITLE
Not able to see Subscribe button

### ISSUE THREAD

**Issue by PallaviBodepudi** [tableau/VizAlerts#148]
Hello,

I have installed ViZAlerts and completed setup as guided
Using tableau 2019.1 and Vizalert 2.1.1. I have enabled trusted authentication and the first test is pass. 
the issue now is i am not able to see "Subscribe button for views" after enabling trusted authentication to test the second test. (Simple Alert Test)

I have one subscription in enable mode, however "VizAlerts - Every 1 hour" is in disable mode as instructed. Am i missing any settings here?
[VizErrors.docx](https://github.com/tableau/VizAlerts/files/3186334/VizErrors.docx)

**Comment by jdrummey** [comment]
Hi, this is not a place for tech support issues, please submit those to http://community.tableau.com/vizalerts.

In any case if you are not seeing a Subscribe button on Tableau Server then it means that your Tableau Server login does not have permissions for subscriptions and/or Subscriptions have not been enabled on Tableau Server. You'll need to check both.

If you need further assistance on this please post your issue at http://community.tableau.com/vizalerts, thanks!

Jonathan
