### ISSUE TITLE
Customize Vizimage link?

### ISSUE THREAD

**Issue by lalato** [tableau/VizAlerts#152]
I'm wondering if this is an option.  I would like to customize the VIZIMAGE vizlink so that it takes the user to a different site where the dashboard is embedded.  Is this possible?

Something along the lines of `VIZIMAGE(MyDashboard/MyView|vizlink:https://MyOtherServer/MyEmbeddedDashboard)`

**Comment by jdrummey** [comment]
Hi, so far as I can remember that’s not an option right now... Theoretically you could create the HTML with the <a href...> then have the VIZ_LINK() content reference then close that with a </a>, but I haven’t tried it.

Jonathan

**Comment by lalato** [comment]
Oh... so you're thinking something along these lines... 
<a href="http://MyOtherServer/MyEmbeddedDashboard">VIZIMAGE(MyDashboard/MyView)</a>

I'll give it a shot and see if it works.

**Comment by jdrummey** [comment]
Sorry, yes, I mean a VIZIMAGE() inside the link.

**Comment by lalato** [comment]
That appears to be working.  Thanks for the tip.
