### ISSUE TITLE
Vizalert cannot receive mail

### ISSUE THREAD

**Issue by Bruceliu123** [tableau/VizAlerts#156]
Hello, may I ask a question about vizalerts?We configured it according to the installation instructions in simple alert test.
The log shows that the message was sent, but i do not received
We don't know what the problem is,How to solve it?

**Comment by AirCooledNut** [comment]
I recommend posting a detailed question in the Tableau community VizAlerts forum at https://community.tableau.com/groups/tableau-server-email-alert-testing-feedbac/content
Things like Tableau Server version, VizAlerts version, log file attached (not dumped in the body of the post), what you’ve tried, etc. can really help to quickly trouble-shoot the issue.  In this case, more information about how your email (SMTP) is set up would be helpful.

Thank you,
   Toby Erkson, Server Administrator for Tableau, Alation, Alteryx, & Power BI

**Comment by Bruceliu123** [comment]
Tableau Server version:2019.3 
VizAlerts version,  v2.1.1
![1572846855(1)](https://user-images.githubusercontent.com/57335340/68101714-fd3e0700-ff09-11e9-8f38-1ca50090cb7a.jpg)

**Comment by Bruceliu123** [comment]
![1572847052(1)](https://user-images.githubusercontent.com/57335340/68101796-6a519c80-ff0a-11e9-90d2-8ee76d283ebe.jpg)

**Comment by mcoles** [comment]
Hi @Bruceliu123 , the email is indeed being sent correctly. Something is happening to it between when it is sent to the SMTP server and when it gets to your inbox, however. That can be for several different reasons. You should look into the following:

- Did a rule on your mail client put it into a different folder?
- Did it get marked as spam?
- Did it go into a Clutter folder (on MS servers)?
- Did the mail server itself prevent it from being delivered? (you may need to ask your IT department,)

One of those things is the likely culprit.

**Comment by Bruceliu123** [comment]
thanks for your help,just&nbsp; as you say&nbsp; it get marked as spam😂



---Original---

**Comment by mcoles** [comment]
Thanks for confirming! If you could direct questions to the [VizAlerts Group on the Tableau forums](https://community.tableau.com/vizalerts) in the future, we'd appreciate it! We use the Issues page here for bugs and feature requests.
