### ISSUE TITLE
Put VizAlerts Through Its Paces Test failed

### ISSUE THREAD

**Issue by Bruceliu123** [tableau/VizAlerts#157]
i enter a comment with the text “test_alert” then run vizalerts.exe,but return a total of 0 alerts,
and vizAlertsConfig workbook contains the record 
![20191105_171603](https://user-images.githubusercontent.com/57335340/68194624-53857580-fff0-11e9-914a-3ec1d3e8fcac.jpg)
![20191105_171730](https://user-images.githubusercontent.com/57335340/68194625-53857580-fff0-11e9-98bc-229597c1739a.jpg)

**Comment by Bruceliu123** [comment]
![20191105_172719](https://user-images.githubusercontent.com/57335340/68195388-bf1c1280-fff1-11e9-8fdc-b9aac2081af0.jpg)
server:2019.3
vizalerts:2.1.1

**Comment by jdrummey** [comment]
Hi,

First of all try running vizalerts.exe a second time. Sometimes on its first run it picks up a task but isn't able to process it (I forget all the details why) and then it processes it on the second run.

Also is the user who entered the test_alert the same user who is the owner of the viz that the test_alert was added to?

Finally, we try not to use the Issues section here on Github for support, in the future please use the Tableau Community site at https://community.tableau.com/groups/tableau-server-email-alert-testing-feedbac, thanks!

Jonathan

**Comment by Bruceliu123** [comment]
i have run it again,but it is the same, and the user is the same user
