### ISSUE TITLE
Unable to cleanup temp directory fatal error when file in temp directory is open

### ISSUE THREAD

**Issue by jdrummey** [tableau/VizAlerts#16]
When a file in the temp directory is open for editing (such as when someone is checking to see what was sent) VizAlerts generates an "ALERT: VizAlerts failed to execute properly" email with the message "Unable to cleanup temp directory .\temp\, error:". This halts all other VizAlerts processing.

I don't think this should be a fatal error, I think it's more of a warning condition. My suggestion would be for VizAlerts to ignore the locked file while it cleans up the rest of the files and generate the warning.

Jonathan

**Comment by mcoles** [comment]
Added into bug fixes branch, will integrate from there into dev, then master. Closing issue!
