### ISSUE TITLE
The CSV attachment file only sent to email once

### ISSUE THREAD

**Issue by TNS-reaj** [tableau/VizAlerts#163]
Hi,

VizAlerts testing workbook CSV attachment: 
After publishing the workbook, I added test_alert to the comments, subscribed to the workbook, and manually ran vizalerts.exe. Then I received an email with the attached CSV file. 
But if I set the task scheduler to run the vizalerts.exe, I receive an email without the attached CSV file. Did I do anything wrong in here? 
Why did the VizAlerts only trigger once when it was manually running and didn't trigger when it was run by Task Scheduler?

Thank you for your help

**Comment by mcoles** [comment]
Hi Jen. Some more questions:

When you ran Task Scheduler, did you allow it to run by itself, or did you trigger it manually?
Did you use a test_alert comment in conjunction with the Task Scheduler, or did you just let it pick up the alert as it was scheduled?
Is Task Scheduler running every 1 minute?
Is the schedule that you subscribed to your alert on disabled?
What do the logs say?

**Comment by TNS-reaj** [comment]
Hi Matt, 
The Task Scheduler runs by itself. 
I tried with or without test_alert comment but the result is the same. I let it pick up the alert as it was scheduled.
Task Scheduler is running every 1 minute.
The schedule is enabled. I have tested, if the schedule is disabled, then there is no email send out.

**Comment by TNS-reaj** [comment]
[log_072920.txt](https://github.com/tableau/VizAlerts/files/4997117/log_072920.txt)

**Comment by mcoles** [comment]
[VizAlerts will not work if the schedules are enabled.](https://github.com/tableau/VizAlerts/issues/162#issuecomment-659687625). If you cannot resolve that issue yourself, please engage with our Sales consulting team or with DataBlick for further support, as I asked previously.

**Comment by TNS-reaj** [comment]
The previous issue found out that the certificate had a problem and finally solved it. Thanks for the suggestion.

**Comment by TNS-reaj** [comment]
I want to share the result here. 
After I unchecked Start the task only if the computer is on AC power in the Task Scheduler Conditions tab, the Task Scheduler to run the vizalerts.exe same as manually run it.  The issue has solved.

**Comment by mcoles** [comment]
Thank you for following up! Glad to hear you figured it out.
