### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by TNS-reaj** [tableau/VizAlerts#164]
Hi,
Does anybody have experience working on VizAlerts with securesend or sendfiles to send sensitive data in the report? How do you guys send a report that contains sensitive data via VizAlerts?
Thanks

**Comment by mcoles** [comment]
VizAlerts only supports SMTP email and SMS messages, which it doesn't look like these other solutions would integrate with. So you'd have to write code to do that yourself, if you wanted it. VizAlerts will allow you to encrypt using TLS, but it doesn't make email inherently secure like some other mediums.

**Comment by TNS-reaj** [comment]
Thanks Matt.
