### ISSUE TITLE
vizalerts.exe missing

### ISSUE THREAD

**Issue by nicklilley** [tableau/VizAlerts#167]
Hi all,

I've searched high and low but can't find the vizalerts.exe anywhere in my installation (even after running build.bat). Has this been removed in favour of the Python install method?

![image](https://user-images.githubusercontent.com/11143685/91387055-f3094280-e866-11ea-8c43-35bbe81c4fc3.png)

**Comment by nicklilley** [comment]
Silly me, I need to run the build.bat file as an Administrator. Looks like my security settings were preventing the .exe from being built. 

As a side note, you might want to add the running of the build.bat file (as an admin) to the install documentation for simple folk like me.

**Comment by mcoles** [comment]
Hi @nicklilley , actually what you want to do is download the zip file from [here](https://github.com/tableau/VizAlerts/releases). Wayyyy easier than building it yourself!
