### ISSUE TITLE
The Advanced function data into VIZ_CSV() report 

### ISSUE THREAD

**Issue by TNS-reaj** [tableau/VizAlerts#170]
Hi,
When I set up the advanced email, the Email Action, Email Subject, Email body, and Email Attachment are in the details with the report data on the same page. (see screenshot #20). If these Advanced tabs do not in the details then the Advanced alerts don't work. 
In the tableau report, the data is fine. (see screenshot #21).
When I received the vizalerts notification email with the attached CSV file, the CSV file report data include Email Action, Email Subject, Email body, and Email Attachment data. How did this happen?  
Please advise.

![20](https://user-images.githubusercontent.com/65303850/96075148-6ea36b00-0e78-11eb-9d41-c5f6e7aaaac4.JPG)
![21](https://user-images.githubusercontent.com/65303850/96075159-73681f00-0e78-11eb-9ff0-87161d51bb4d.JPG)
![22](https://user-images.githubusercontent.com/65303850/96075167-77943c80-0e78-11eb-88b0-ce4767e96e3a.JPG)

Thanks

**Comment by jdrummey** [comment]
Hi,

This is expected behavior. The VIZ_CSV() content reference is pulling down all the fields used in the visualization (everything on Columns, Rows, Pages, and the Marks card) so that includes the Email fields.

What you need to do is build two views: one that has the email fields and is subscribed, and the second that has the content for the VIZ_CSV() content reference with just the fields you want included in the attachment. I'm sorry this wasn't clear in the documentation, if there's something that you can point at to help us clarify that distinction for Advanced Alerts we'd be glad to add it!

Jonathan

**Comment by TNS-reaj** [comment]
Hi Jonathan,
Do you have an example of building two views that you mentioned here? Not sure how this exactly looks.

Thanks

**Comment by jdrummey** [comment]
Take a look at the VizAlertsDemo workbook test alerts https://github.com/tableau/VizAlerts/blob/master/docs/install_guide.md#put-vizalerts-through-its-paces-test... The VizAlertsDemo/AdvancedAlerts view shows a number of Advanced Alerts that have been configured. This view has the Email fields and then the content references are pointing at other views (which happen to be in this workbook, but could be entirely other workbooks).

Jonathan

**Comment by TNS-reaj** [comment]
Hi Jonathan,
I have reviewed VizAlertsDemo and tried it again. When I copied AdancedAlerts view from Demo to my workbook then configured them with our info and added them to the Detail shelf (see screenshot #23). Then copied these AdvancedAlerts files to the workbook view which I need to send an email out(see screenshot #24). When I received an email, I only received a simple alert. The VizAlerts doesn't recognize AdvanceAlerts. Only when I add these AdvanceAlerts to the detail shelf in my workbook then the VizAlerts will send advanced alerts to my email but the CSV file report data will include Email Action, Email Subject, Email body, and Email Attachment... data.
Do I miss anything in the step?

Thanks

![23](https://user-images.githubusercontent.com/65303850/96291821-a57f9b00-0fb6-11eb-80ca-22948359560f.JPG)
![24](https://user-images.githubusercontent.com/65303850/96291828-a9abb880-0fb6-11eb-8408-908d7f039a55.JPG)

**Comment by TNS-reaj** [comment]
Hi Jonathan,
I tried to republish the vizalerts\demo Advanced Alerts (tests) again and found the errors. See below. The server doesn't have any block. Why the 404 error in here?
Please advise.

2020-10-19 10:32:14 - [ERROR] - HTTP error getting vizdata from url 
https://xxxxxxxxxx.edu/views/VizAlertsDemo/Product?Region=West&amp;:format=pdf&amp
;:refresh=y. Code: 404 Reason: Not Found
2020-10-19 10:32:14 - [ERROR] - Unable to render content reference VIZ_PDF(VizAl
ertsDemo/Product?Region=West|filename=WestSales|mergepdf) with error:<br> HTTP e
rror getting vizdata from url https://xxxxxxxxxx.edu/views/VizAlertsDe
mo/Product?Region=West&amp;:format=pdf&amp;:refresh=y. Code: 404 Reason: Not Fou
nd
2020-10-19 10:32:14 - [ERROR] - Alert was triggered, but encountered a failure g
etting data/image references:<br /> Unable to render content reference VIZ_PDF(V
izAlertsDemo/Product?Region=West|filename=WestSales|mergepdf) with error:<br> HT
TP error getting vizdata from url https://xxxxxxxxxx.edu/views/VizAler
tsDemo/Product?Region=West&amp;:format=pdf&amp;:refresh=y. Code: 404 Reason: Not
 Found
2020-10-19 10:32:14 - [ERROR] - Unable to process alert Advanced Alerts Demo as
csv, error: Alert was triggered, but encountered a failure getting data/image re
ferences:<br /> Unable to render content reference VIZ_PDF(VizAlertsDemo/Product
?Region=West|filename=WestSales|mergepdf) with error:<br> HTTP error getting viz
data from url https://xxxxxxxxxx.edu/views/VizAlertsDemo/Product?Regio
n=West&amp;:format=pdf&amp;:refresh=y. Code: 404 Reason: Not Found
2020-10-19 10:32:14 - [DEBUG] - All errors found:
2020-10-19 10:32:14 - [DEBUG] - Unable to render content reference VIZ_PDF(VizAl
ertsDemo/Product?Region=West|filename=WestSales|mergepdf) with error:<br> HTTP e
rror getting vizdata from url https://xxxxxxxxxx.edu/views/VizAlertsDe
mo/Product?Region=West&amp;:format=pdf&amp;:refresh=y. Code: 404 Reason: Not Fou
nd


Thanks

**Comment by jdrummey** [comment]
Hi, a 404 error in this case means that the VizalertsDemo workbook either hasn't been published, or was published under a different name, or there aren't sufficient permissions to access the workbook.

A good test is to a) copy the URL from the log, b) in your web browser log into Tableau Server using the VizAlerts run-as user, and c) then paste the URL in to go to that. If you can't log in or see the URL from your web browser using the Vizalerts run-as user then VizAlerts won't be able to either, and you'll need to diagnose what's going on.

Jonathan

**Comment by jdrummey** [comment]
re: your earlier post with the screenshots there's too little information for me to see what's going on and help you. For example I can't see the values of the Email Action, Email Subject, Email Attachment, etc. fields. So let me try to give you an example from our production configuration of VizAlerts:

For one of our projects the use case is to email out a set of dashboards as PDFs on a monthly basis to some users. The configuration is as follows:

1. The Advanced Alerts trigger view is located in the view VizAlerts1/EmailDistrict1 (i.e. VizAlerts 1 workbook, Email District 1 worksheet). It's built as a simple text table so we can easily review all the values and is configured to have one row per alert. Note that it has the Email Action field that tells VizAlerts to treat this as an Advanced Alert and not a Simple Alert:

![2020-10-19_11-59-07](https://user-images.githubusercontent.com/376369/96475904-8ffeb100-1202-11eb-8afd-d9c3e5d906e0.png)

The VIZ_PDF() content reference that is in the Email Attachment District 2 field is pointing to views in another workbook in the site, in this case the full content reference is something like VIZ_PDF(ZambiaMalariaReportingDashbords/Risk-Overview-District?District=ce%20%Chibombo%District). 

2. The trigger view from #1 is published to Tableau Server and subscribed to one of the VizAlerts subscriptions that have been configured as a disabled subscription per the VizAlerts install guide.

3. When VizAlerts runs on the monthly schedule it downloads the trigger view from VizAlerts1/EmailDistrict1, then per the configuration of the each row of the trigger view downloads the content references from other views, assembles each email, and delivers the emails.

I hope this helps! My suggestion for you from here would be to:

1. Set up an Advanced Alert trigger view as a separate worksheet and built it in text table form like the one above with all Email fields as discrete (blue) fields on Rows.

2. Validate that the VIZ_CSV() content reference is accurate per the instructions at https://github.com/tableau/VizAlerts/blob/master/docs/user_guide.md#custom-view-references-getting-almost-any-view-from-tableau-server

3. Try to run the advanced alert by going to the trigger view from step 1 and using test_alert.

4. If that doesn't work and you're not able to debug what's going on, then post again here with a screenshot of the entire trigger view window including the Rows, Columns, and Marks Card displayed (like the screenshot I'd posted above).

Regards,

Jonathan

**Comment by TNS-reaj** [comment]
The 404 link is 

https://xxxxxx.edu/views/VizAlertsDemo/Product?Region=West&amp;:format=pdf&amp;:refresh=y.

But I can open the demo file in tableau with the below link:

https://xxxxxx.edu/#/views/VizAlertsDemo_15955180561540/DataForDownload?:iid=3

I see the difference between these two links is the #/ before the views missing in the error link
https://xxxxxx.edu/#/views/

Any thoughts?

Thanks

**Comment by TNS-reaj** [comment]
The VisAlertsDemo is under the Explore / Default

**Comment by jdrummey** [comment]
Hi,

The two URLs you gave are actually different views (first is Product, second is DataForDownload) from different workbooks (first is VizAlertsDemo, second is VizAlertsDemo_15955...).

For VizAlerts to run and pull content references the referenced workbook/viewname has to match exactly. My guess is that the Viz Alerts Demo workbook was already published (and perhaps removed?) from Tableau Server, and then the one that you are accessing now was published at a later time because the added _###########  to the end is standard behavior for Tableau when two workbooks are published with the same name. (The first workbook with that name uses the workbook name, the second workbook gets a unique # appended to the name).

There are a couple of options here to use the VizAlertsDemo workbook: One is to make sure that you have access to the original VizAlertsDemo workbook, the other would be to update the content references in the trigger view of the VizAlertsDemo workbook to point to it's new workbook name of VizAlertsDemo_15955...

Jonathan

**Comment by TNS-reaj** [comment]
Hi Jonathan,
The VizAlertsDemo issue fixed. 
I have create another view called Advanced Alerts with all the Email Action*,Email Attachment.. etc.  (See screenshots #27-#31). Email Attachment point to the view which I want to attached csv file in the email. (see screenshot #33 and #31).  After run the test, I have received email with all correct subject, email body..., and attachment csv file. (See screenshot #34). But the csv file data is incorrect. (see screenshot #35). The correct data shows in screenshot #33. Not sure how this happened. 
Please advise.
Thank you!
![27](https://user-images.githubusercontent.com/65303850/96778767-1dd0cc80-13ba-11eb-90bc-4e649a1332bb.JPG)
![28](https://user-images.githubusercontent.com/65303850/96778780-21fcea00-13ba-11eb-9521-c86a1ae351c6.JPG)
![29](https://user-images.githubusercontent.com/65303850/96778798-275a3480-13ba-11eb-9144-bd03e8ecd6a1.JPG)
![30](https://user-images.githubusercontent.com/65303850/96778799-275a3480-13ba-11eb-97c4-f792949c656c.JPG)
![31](https://user-images.githubusercontent.com/65303850/96778800-275a3480-13ba-11eb-90cf-9de222b8f428.JPG)
![33](https://user-images.githubusercontent.com/65303850/96778819-2d501580-13ba-11eb-97e0-b25e338561fd.JPG)
![34](https://user-images.githubusercontent.com/65303850/96778820-2d501580-13ba-11eb-974c-e78ac7c31514.JPG)
![35](https://user-images.githubusercontent.com/65303850/96778821-2d501580-13ba-11eb-9001-5899f26dcff0.JPG)

**Comment by TNS-reaj** [comment]
It seems the VIZ_CSV() didn't point the correct view.

**Comment by jdrummey** [comment]
Hi, the VIZ_CSV() reference is just the workbook/viewname, so VIZ_CSV(PreBillingDEV102120/Pre-billEstimatedBill) or something like that (I'm not sure if the =Pre-billEstimatedbill is actually part of the view name or an attempt at adding a URL parameter as a filter).

**Comment by TNS-reaj** [comment]
When I put the reference in VIZ_CSV(PreBillingDEV102120/Pre-billedEstimatedBill), I received an error.

General errors:
Unable to render content reference VIZ_CSV(Pre-billed_Estimated_Bill) with error:
HTTP error getting vizdata from url https://xxxxxxxxxx.edu/views/Pre-billed_Estimated_Bill?&:format=csv&:refresh=y. Code: 404 Reason: Not Found

Unable to process alert Advanced Alerts as csv, error: Alert was triggered, but encountered a failure getting data/image references:
Unable to render content reference VIZ_CSV(Pre-billed_Estimated_Bill) with error:
HTTP error getting vizdata from url https://xxxxxxxxxx.edu/views/Pre-billed_Estimated_Bill?&:format=csv&:refresh=y. Code: 404 Reason: Not Found

Alert Information:

View URL: https://xxxxxxxxxx.edu/views/PreBillingDEV102120/AdvancedAlerts
Subscriber: xxxx
View Owner: xxxx
Site Id: Default
Project: xxxxxxxx

I tried many different ways, the only email I can receive without error is 'VIZ_CSV(/#/views/PreBillingDEV102120/Pre-billedEstimatedBill=Pre-billed_Estimated_Bill)' but the attached CSV file data incorrect. 

This view in the tableau link is https://xxxxxxxxxx.edu/#/views/PreBillingDEV102120/Pre-billed_Estimated_Bill?:iid=2.

Any thought?
Thanks

**Comment by TNS-reaj** [comment]
The additional question:
The CSV output file columns are ordered by alphabet letters. Is there any way can set the CSV output file order like the Tableau report?
