### ISSUE TITLE
Helpme Unable to process alert PDF Merge as csv, error: Alert was triggered, but encountered a failure getting data/image references: Unable to render content reference

### ISSUE THREAD

**Issue by AngelCastillo15** [tableau/VizAlerts#171]
The following errors were encountered trying to process your alert:

General errors:

Unable to render content reference VIZ_PDF(ControldeContenedoresRefrigeradosEspecialesenPatio0600/Lista|filename=SCReefers|mergepdf) with error:
Timeout error. Could not retrieve vizdata from url https://hes32-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=http%3a%2f%2fmitinsighttab1.panama.int%2fviews%2fControldeContenedoresRefrigeradosEspecialesenPatio0600%2fLista%3f%26%3aformat%3dpdf%26%3arefresh%3dy&umid=714b17cc-7674-4fd6-a27a-2f2190582f86&auth=7cdaf58d94de80a577ae943a8c37ae9363e90c73-e7185513f16c069279b0ee86973fba0e2497c0ea within 300 seconds, after 2 tries

Unable to process alert PDF Merge as csv, error: Alert was triggered, but encountered a failure getting data/image references:
Unable to render content reference VIZ_PDF(ControldeContenedoresRefrigeradosEspecialesenPatio0600/Lista|filename=SCReefers|mergepdf) with error:
Timeout error. Could not retrieve vizdata from url https://hes32-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=http%3a%2f%2fmitinsighttab1.panama.int%2fviews%2fControldeContenedoresRefrigeradosEspecialesenPatio0600%2fLista%3f%26%3aformat%3dpdf%26%3arefresh%3dy&umid=714b17cc-7674-4fd6-a27a-2f2190582f86&auth=7cdaf58d94de80a577ae943a8c37ae9363e90c73-e7185513f16c069279b0ee86973fba0e2497c0ea within 300 seconds, after 2 tries

**Comment by mcoles** [comment]
Please see issue #177 , as the remedy will be the same.
