### ISSUE TITLE
Vizalert email attached csv file empty

### ISSUE THREAD

**Issue by shirinnn** [tableau/VizAlerts#172]
Hi,

I would like to ask what is the possible cause of the attached empty csv excel file in the email generated by Vizalert.
I have check the format use and it is correct(VIZ_CSV(workbookname/viewname)) and in tableau server the view that is reference in viz_csv() have data in it.

Unable able to share screenshots due to organisation unable to upload stuff to external sites

**Comment by mcoles** [comment]
Are you referencing a dashboard? If so, then the CSV exported will be from the sheet with the name that comes before the others, alphabetically. So you may expect a sheet that you are not getting, which is actually empty of data. You can troubleshoot more directly by using URL parameters to export the CSV you want, as https://yourserver/views/yourworkbook/yoursheet?:format=csv

**Comment by shirinnn** [comment]
Okay thanks! Noted on this.
