### ISSUE TITLE
Unable to render content reference. Timeout error

### ISSUE THREAD

**Issue by shirinnn** [tableau/VizAlerts#177]
Hi,

Hit this issue when using Vizalert:

Unable to process alert Email List - 1130am as csv, error: Alert was triggered, but encountered a failure getting data/image references:
Unable to render content reference VIZ_IMAGE(DailyLimitsMonitoring/MonitoringDetails|vizlink) with error:
Timeout error. Could not retrieve vizdata from url https://{domain}/views/DailyLimitsMonitoring/MonitoringDetails?&:format=png&:size=1500,1500&:refresh=y within 700 seconds, after 1 tries

What might be the cause of this? 
Might it be due to the size of the dashboard or will the query affect which cause a timeout?
How does VIZ_IMAGE works?

Thank you!

**Comment by mcoles** [comment]
VIZ_IMAGE() makes a call to the viz referenced within the parenthesis that exports the PNG, e.g. **https://yourserver.com/views/DailyLimitsMonitoring/MonitoringDetails?:format=PNG** . The error indicates that this operation took longer than 700 seconds, which was beyond the timeout setting for it. Does this viz normally take this long to render? Or does this seem like an anomaly? Keep in mind that when VizAlerts requests the PNG, it is passing the :refresh=y parameter, which forces a data refresh to ensure no caching is used. If it normally takes this long, you can either increase the timeout setting by tweaking the timeout_s calc in the VizAlertsConfig workbook, or you can edit the viz to improve rendering performance.

**Comment by shirinnn** [comment]
This seem like anomaly. This issue only happens intermittently. Most of the time, we did not receive this issue. The viz does not take 700 seconds to render too. 
So might this be a server issue instead?

**Comment by mcoles** [comment]
Yes, it is a Server issue. The only relevancy a timeout has to VizAlerts is the threshold at which it decides the request timed out. If your viz connects live to a database server, it's possible it was suffering performance issues at the time, or perhaps engaged in a maintenance task, or blocking may have been occurring (if using older platforms).

**Comment by shirinnn** [comment]
okay noted on this. Thanks a lot for the explanation to help me understand!
