### ISSUE TITLE
Unable to generate trusted tickets since we move our tableau server from HTTP to HTTPS

### ISSUE THREAD

**Issue by ericknizard** [tableau/VizAlerts#179]
does anyone know what part needs to be updated for it to function again

![image](https://user-images.githubusercontent.com/32941736/109836414-1fd15480-7c12-11eb-83f3-52184f7c32d0.png)

**Comment by mcoles** [comment]
Here are a couple similar issues:

https://community.tableau.com/s/question/0D54T00000C5MchSAF/viz-alerts-issue
https://community.tableau.com/s/question/0D54T00000C5MxISAV/issuw-with-the-viz-alert

I would expect that having a proxy or load balancer in front of Tableau Server could also cause this, but that seems less likely...

**Comment by mcoles** [comment]
Thanks @ericknizard -- would you mind letting us know what the solution was?

**Comment by ericknizard** [comment]
we needed to configure the # Security settings in the .yaml file

**Comment by mcoles** [comment]
thanks!
