### ISSUE TITLE
Timeout error. Could not retrieve vizdata from url

### ISSUE THREAD

**Issue by miralvaghela** [tableau/VizAlerts#185]
Hi team, 

We're receiving below errors while generating view from vizalert. Is there any specific setting I need to apply? I have attached our vizalert yaml config file. Please let us know do we need to change anything.

**Comment by jdrummey** [comment]
Hi,

It looks like you'd already asked about the first error at https://community.tableau.com/s/question/0D54T00000xU7nXSAS/hi-everyone-im-receiving-a-timeout-error-for-one-of-my-vizalert-view-i-have-pasted-log-in-the-details-tab-can-you-please-guide-me-to-fix-it-is-there-any-configuration-which-i-suppose-check-so-this-view-was-working-fine-before and that's been answered there.

For the second error that's coming from VizAlerts attempting to notify the alert owner about the error sending the alert. I'm thinking the vizalerts.yaml file hasn't been properly configured, here's the relevant documentation: https://github.com/tableau/VizAlerts/blob/master/docs/install_guide.md#configure-vizalerts

**Comment by miralvaghela** [comment]
Hi Jonathan,

Thank for your support. I have checked our config file and we have specified below values when we configured and it is same as before. We didn’t change anything recently. Please let me know what else should I check.

smtp.port: 25                                   # port to user for SMTP server (default is 25)
smtp.address.from: .***@***.******@***.***\.com>     # default sender for all alerts mail
smtp.address.to: ***@***.******@***.***>      # email address of admin to send failures to


Thanks
Miral Vaghela.

**Comment by ericknizard** [comment]
@jdrummey,

in our yaml file, we have the 'smtp.address.from' option configured as follow ".*@ourcompany\.com".

we understood the way to set this option as "anyone that has an @ourcompany.com" email address so that depending on the type of content we want to send via vizalert we can use the Send From as "sales@ourcompany.com" or "finance@ourcompany.com", etc...

Did we configured the setting in the yaml file correctly ? or should the yaml setting be a full email such as "vizalerts@ourcompany.com" and then at the individual vizalert we can override it by using "sales@ourcompany.com" or anything else?

Apologies for the dumb question

Best

**Comment by jdrummey** [comment]
Hi,

There are no dumb questions!

The smtp.address.from needs to be a singular email address like any from address. See https://github.com/tableau/VizAlerts/blob/master/docs/install_guide.md#configure-vizalerts for details on that. This is the From address used for notifications to alert owners on failed alerts as well as the default From address for advanced alerts if there's no Email From field.

The configuration of the allowed set of from addresses is done in the VizAlertsConfig Tableau workbook in the allowed_from_address parameter. See https://github.com/tableau/VizAlerts/blob/master/docs/install_guide.md#open-the-vizalertsconfig-workbook (an earlier section in the documentation) for those details.  Also note that the regex needs to be slightly different: ".*@ourcompany\.com".

**Comment by ericknizard** [comment]
great thanks ! that's probably our mistake ! we will update both the yaml and the vizalertconfig workbook and verify it solves the issue

**Comment by jdrummey** [comment]
Let us know how it goes!

**Comment by ericknizard** [comment]
looks like it does the trick ! thanks Jonathan !

**Comment by miralvaghela** [comment]
Thanks for your help !!
