### ISSUE TITLE
VizAlertsConfig "ERROR: current transaction is aborted" following upgrade Tableau Server to 2021.4.1 

### ISSUE THREAD

**Issue by westmalle** [tableau/VizAlerts#189]
We just upgraded TS from 2020.3 to 2021.4.1 and vizalerts seems broken. VizAlerts version is 2.1.1
The VizAlertsConfig worksheet returns an error:
Unexpected Server Error
TableauException: ERROR: current transaction is aborted, commands ignored until end of transaction block;
Error while executing the query
The data source connection works fine when testing from Tableau Server "Edit Connection", but the SQL query returns the error.
The SQL query runs ok in a SQL client tool with the same "readonly" user.
Any idea how to solve ?

**Comment by westmalle** [comment]
![vizalert_config_error](https://user-images.githubusercontent.com/7202319/146513525-c0c43760-df00-4f51-9249-37236892e352.png)
![vizalerts_custom_sql_client](https://user-images.githubusercontent.com/7202319/146513544-869ac636-5779-41af-9925-7bdbb00e061f.png)

**Comment by westmalle** [comment]
I noticed that converting the data source from live to extract, the extract refresh works. Problem seems only to appear when connecting live.

**Comment by mcoles** [comment]
Most likely due to the PostgreSQL upgrade that requires a new driver. Same issue this person had: 
https://community.tableau.com/s/question/0D54T00000bjE3e/we-did-an-upgrade-to-20211-this-week-and-have-an-outstanding-issue-with-the-admin-reports-that-connect-to-the-postgresql-data

**Comment by westmalle** [comment]
Thanks Matt.
I tried to update the driver by following the instructions (for linux)
![driver_postgresql_tableau](https://user-images.githubusercontent.com/7202319/146747919-9eb11ce5-732a-4f3b-be40-25a1fb50958f.png)
I put the downloaded driver (postgresql-42.2.22.jar) in /opt/tableau/tableau_driver/jdbc
![opt_driver](https://user-images.githubusercontent.com/7202319/146749481-314b5383-0a78-4d0a-bc88-65861150709f.png)

After that, when I try to connect to TS postgresql database, it hangs for a while (1 minute) and returns an error :
![connection_failed](https://user-images.githubusercontent.com/7202319/146748973-c3b47547-a215-456a-912a-3fab7ef48cd1.png)

**Comment by westmalle** [comment]
I found the solution : just restart tableau server after installing the driver !
