### ISSUE TITLE
VizAlerts performance issues after upgrading Tableau Server to 2021.4

### ISSUE THREAD

**Issue by FSMA-au** [tableau/VizAlerts#192]
Performance of VizAalerts has degraded significantly after we upgraded from Tableau Server 2020.4 to 2021.4. We have log files that show that visualisations now take almost twice as long to run in VizAalerts as they did previously. This is impacting significantly on our ability to deliver visualisations to this business in a timely manner each morning.

Just wondering if anyone else has encountered and/or resolved this issue?

Cheers.

**Comment by mcoles** [comment]
Hi!

I'm not aware of any reason to expect such a degradation. Problems like this typically have nothing to do with VizAlerts, and are either an issue with Tableau Server, back-end databases, drivers, or sometimes (but rarely in my experience) networking. Some questions to help narrow down where the problem is.... :

Do the vizzes you are sending use live connections to a database, or are they based on extracts? Do they connect through published data sources? Have you noticed any other performance issues with vizzes rendered in-browser by users (ideally this would be based on performance data you are monitoring).

**Comment by jdrummey** [comment]
I haven't encountered this either. My first thought would be to debug by logging into Tableau Server in a web browser and loading up the slow trigger views or content reference views...if the views are also slow to render in the web browser then you can rule out VizAlerts and start digging into everything Matt mentioned.

**Comment by FSMA-au** [comment]
Hi Matt - thanks for the reply.

The vizzes in question are connecting to a published live data source (to an Oracle database view). Most of our vizzes normally do use extracts - however these vizzes run very early in the morning - before the extracts have completed, so we use a live datasource instead for these.

Initially we assumed the issue was poor Tableau performance - however we have not seen a noticeable degradation in interactive performance.

Comparing the VizAlert log files from before and after the upgrade shows that the same vizzes are taking approx. twice the time they took previously.  For example, a pdf viz in VizAlert that ran in 1min 30 sec before is now running in 2min 50 sec.

Quite clearly these are slow vizzes in the first place - but this is because they are using a large live datasource.  The original performance wasn't an issue because no-one uses these vizzes interactively - they are only run using VizAlerts.

Your reply prompted me to consider if I can reduce the size of the datasource - to see if this improves performance.  The datasource contains data for approx. 4 years - however the dashboards we are using it for only ever show current year and previous year, so I am going to add a filter to the Oracle database view to limit the data to 2 years and see if this reduces the run time for these vizzes.

Thanks again for your assistance.

Cheers,
Darran

Darran Ambrose
Business Intelligence Manager
National Pharmacies I National Support Office
52 Gawler Place, Adelaide SA 5000
T - 08 8223 0328   M - 0411 484 213
E - ***@***.******@***.***>
www.nationalpharmacies.com.au<http://www.nationalpharmacies.com.au/>
***@***.***
