### ISSUE TITLE
problem upgrading to 2.2.0 from 2.1.1

### ISSUE THREAD

**Issue by cyberoner1** [tableau/VizAlerts#197]
Hi,
System Windows 2016
removed Python 2
installed python 3.9.13 
installed all recommended moduls
updated config twb
copied vizalert.yaml to new folder

when i now run python vizalerts.py I am getting following error

An exception was raised loading the config file .\config\vizalerts.yaml: (<class
 'TypeError'>, TypeError("load() missing 1 required positional argument: 'Loader
'"), <traceback object at 0x000000A0555A4C80>) Stacktrace: <traceback object at
0x000000A0555A4C80>
Could not initialize configuration file due to an unknown error: 'NoneType' obje
ct has no attribute 'error'

**Comment by cyberoner1** [comment]
I made some progress here. changeing __init__.py line 34 from
yaml_opts = load(f)
        to
... = yaml.safe_load(f)

is now bringing me the same error as I have running the exe

`Could not process source viz data from VizAlertsConfig/ScheduledTriggerViews for the following reason:<br/><br/>Invalid regular expression found. Could not evaluate expression '' in the field allowed_from_address. Raw error:<br/><br/>allowed_from_address`


the regular expression I am using .*

**Comment by mcoles** [comment]
Should be fixed as of 2.2.1, thanks!
