### ISSUE TITLE
Update config workbook to use new projects_contents mapping table

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#203]
Determining which piece of content resides in a specific project is done via the project_id column in today's PostgreSQL schema. However, Tableau 2023.1 will change that, relying instead upon the projects_contents table. The database views built around these content tables should be updated to contain the correct mapping, which could be the best way for us to avoid breaking compatibility with older versions of Tableau by explicitly referencing the new table (I've avoided using the views at times in the past due to the fact that I needed columns that were not exposed in those views).

**Comment by mcoles** [comment]
This _should_ be a fix for it, but need to test on a 2023.1 Tableau Server instance to be sure.

[VizAlertsConfig_2020.4_with_fix.twb.txt](https://github.com/tableau/VizAlerts/files/10273450/VizAlertsConfig_2020.4_with_fix.twb.txt)

**Comment by AirCooledNut** [comment]
Is this INNER JOIN statement in addition to the list of ones near the bottom of the SQL or does it replace the existing ones near the bottom at 
`INNER JOIN workbooks w
           ON v.workbook_id = w.id
        INNER JOIN sites st
           ON v.site_id = st.id
        INNER JOIN projects p
           ON w.project_id = p.id`

**Comment by mcoles** [comment]
It replaces it. Using the workbooks.project_id field is no longer valid, as of 2023.1, so you have to join to projects_contents. Not sure why the code formatter won't let me add line breaks properly...but basically you're

Replacing this:

`INNER JOIN workbooks w`
`    ON v.workbook_id = w.id`
`INNER JOIN sites st`
`    ON v.site_id = st.id`
`INNER JOIN projects p`
`    ON w.project_id = p.id`

...with this:

`INNER JOIN workbooks w`
`    ON v.workbook_id = w.id`
`INNER JOIN sites st`
`    ON v.site_id = st.id`
`INNER JOIN projects_contents pc`
`    ON w.id = pc.content_id`
`        AND pc.content_type = 'workbook'`
`INNER JOIN projects p`
`    ON pc.project_id = p.id`


Those changes could be written more concisely, I know, but I wanted to show how workbooks related to projects in its entirety.

**Comment by AirCooledNut** [comment]
Perfect, just as I thought.  Thanks!

Yeah, I couldn't get the code formatting to work either, thus the messy looking message o' mine.

**Comment by wyllwo01** [comment]
Thank you so much for contributing to this. Looks like Tableau no longer populates the project_id column in the workbook table in version 2023.1? Due to this, VizAlert specification workbooks published after upgrading to Tableau version 2023.1 do not send VizAlerts (since the inner join to the project table on workbook_id filters out workbooks and therefore the VizAlert specifications do not show in the VizAlertsConfig workbook).

Summary: VizAlerts is not compatible with Tableau 2023.1 at least due to this issue.

Do you have an estimate on when this fix will be merged to main?

Thanks!

**Comment by mcoles** [comment]
This is fixed in the v2.2.1 release
