### ISSUE TITLE
merge_pdf_attachments incompatible with MyPDF2 3.0.0 and other packages.

### ISSUE THREAD

**Issue by booseh** [tableau/VizAlerts#205]
Email failed to send: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.
Email failed to send: PdfFileMerger is deprecated and was removed in PyPDF2 3.0.0. Use PdfMerger instead.
send_email - Email failed to send: local variable 'mergedfilename' referenced before assignment

Is there a requirements.txt file available that shows which package versions work with VizAlerts?

**Comment by mcoles** [comment]
There isn't, but should be. I updated the references in the latest version (v2.2.1) just released so I'm closing this, but created #211 to track your request.
