### ISSUE TITLE
VizConfigSQL

### ISSUE THREAD

**Issue by jeff-abraham-rushst** [tableau/VizAlerts#207]
I recently updated tableau server to 2023.1. Since the update, any new workbooks uploaded to the server are showing a project_id of null in the tableau repository workbooks file. This results in the VizConfig custom SQL not returning a row for these workbooks. The query has an INNER JOIN to the projects table on project_id. If this were to change to a LEFT JOIN, would it compromise the functionality of vizalerts?

**Comment by mcoles** [comment]
This is #203 . You can manually edit the VizAlertsConfig workbook CustomSQL to fix.
