### ISSUE TITLE
Upgrading Tableau to 2023.1.2 (Invalid regular expression "allowed_from_address"

### ISSUE THREAD

**Issue by pgibbs2** [tableau/VizAlerts#208]
I've used vizalerts for over a year now working flawlessly.  After upgrading to 2023.1.2 I'm now receiving the following error:

MainThread - 2023-06-26 14:02:05 - [DEBUG] - send_email - email body: Could not process source viz data from VizAlertsConfig/ScheduledTriggerViews for the following reason:<br/><br/>Invalid regular expression found. Could not evaluate expression '' in the field allowed_from_address. Raw error:<br/><br/>allowed_from_address

tried changing allowed_from_address to ".*" and also the data.coldelimiter, but neither of those helped so I set them back to where they were.

**Comment by mcoles** [comment]
Thanks for logging, @pgibbs2. This is an issue that affects VizAlerts but seems to be an issue with on the Tableau Server side. More details, and a potential fix, can be found [here](https://community.tableau.com/s/question/0D78b000008as7HCAQ). Can you let us know if reconfiguring the gateway.public.host config value, then applying changes with a restart resolves it?

**Comment by mcoles** [comment]
Created #209 to improve error messaging when this happens.

**Comment by pgibbs2** [comment]
@mcoles Hi Matt, one thing I'm worried about is our FQDN and the external URL is different.  One user saw from an external tool it redirected to just the machine name.  I'm worried if I change this to the fqdn to fix vizalerts it may cause some other unintentional issues.
