### ISSUE TITLE
Issue #203 is not fixed in vizalerts.zip file in release 2.2.1

### ISSUE THREAD

**Issue by wyllwo01** [tableau/VizAlerts#212]
Issue #203 is not fixed in the vizalerts.zip in release 2.2.1 even though it is mentioned in the release notes. Did the latest changes to VizAlertsConfig.twb make it to this zipped release file?

**Comment by mcoles** [comment]
Sigh...I knew there'd be something. I've updated the binary--would you mind confirming it looks good for you now? Thanks for letting me know.

**Comment by wyllwo01** [comment]
Thanks, a simple VizAlert worked. We haven't done any other testing. Was VizAlertsConfig.twb the only file that wasn't updated?

**Comment by mcoles** [comment]
Missed version_history.txt, fixed that too. Thanks!
