### ISSUE TITLE
Off-line Python install for Windows needed

### ISSUE THREAD

**Issue by AirCooledNut** [tableau/VizAlerts#29]
From this post https://community.tableau.com/message/390189#390189 I was able to install the files _requests_ntlm_ and _requests_.  The file doesn't contain _pypdf2_ since this is a new file needed for this 1.0.0 release.

So for step 3.c. of "Install Python & Required Modules" I had to use the .zip file Matt supplied (above URL) because I could not get the necessary files as suggested in Appendix A of the documentation.  Also, in order to use **pip** the user will need Python installed on the computer they are using in order to get the Python files for their Tableau Server -- that certainly doesn't make things any simpler!

I recommend having the necessary Python files pre-packaged in the .zip file (in their own folder) so they can be used for new installs and ignored for upgrades unless necessary like in my situation.

Note that steps 1, 2, and 3.a & 3.b were easy to do.  I was able to get the _executable_ files, save them locally to my laptop, paste them to my Tableau Server, and then run them as an administrator on my Tableau Server.

**Comment by mcoles** [comment]
I improved Appendix A to address this as a stopgap until we can build an actual installer for VizAlerts (Issue #9). Thanks for catching, Toby!
