### ISSUE TITLE
Change CSV output to use LF instead of CR

### ISSUE THREAD

**Issue by jdrummey** [tableau/VizAlerts#31]
In tabhttpy.py the export_view() function has the following line #211:
`
f.write(response.content.replace('\r\n', '\r'))  # remove extra carriage returns
`

The CR written by \r is a rarely used form of newline, for a single newline character LF (\n) is the much more common character (see https://en.wikipedia.org/wiki/Newline for a discussion). This can cause problem for downstream scripts that are expecting CRLF or LF but not CR.

I propose replacing the \r with a \n for the newline, so the line would be this:
`
f.write(response.content.replace('\r\n', '\n'))  # remove extra carriage returns
`

**Comment by mcoles** [comment]
Did you already implement a fix request, Jonathan? If not, could you branch off of Master, make your change, then submit a pull request to Development please?

**Comment by jdrummey** [comment]
I haven’t made one in the code yet.
