### ISSUE TITLE
Can VizAlerts send notification by Active Directory Group, instead of email addresses?

### ISSUE THREAD

**Issue by M0RR15P0** [tableau/VizAlerts#47]

**Comment by mcoles** [comment]
VizAlerts can email any valid email address that you provide it in your data. Therefore, if you have a table which contains a list of all members of AD groups along with their email addresses, yes, you can pull that into your alert and have it email everyone by AD group. But VizAlerts is not aware of AD groups and what they are; all it cares about is the data you feed it.

Please direct any follow-ups, or further questions to: http://community.tableau.com/vizalerts

thanks!
