### ISSUE TITLE
Compatability of Vizalerts with Tableau server 9.3

### ISSUE THREAD

**Issue by Shobananpa** [tableau/VizAlerts#55]
Hi Team,

I have a question, is the latest version of VizAlerts (v1.1.1) compatible with Tableau server 9.3.

I downloaded VizAlerts v1.1.1 and trying to configure, I'm seeing error message which refers to config.yml file.

Thanks,
Shoba

**Comment by mcoles** [comment]
Yes, it is currently compatible with 8.2.5 all the way to 10.0. Would you please direct any further questions to [our group on the Tableau Community site](http://community.tableau.com/vizalerts)? We can help you troubleshoot there. Thanks!
