### ISSUE TITLE
Allow embedding of customized View content in Advanced Alerts

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#6]
Currently, the only way to receive an alert from a view that dynamically adjusts its content to your own user account on Tableau Server is via a Simple Alert--you must subscribe to it yourself, and everyone else who wants the same thing must also do the same.

Advanced Alerts can push HTML emails with embedded View images in them to any email address(es) desired, but they cannot dynamically render arbitrary View information into them and customize it for the audience it pushes the email to.

This feature would increase the flexibility of an Advanced Alert by allowing the author to instruct VizAlerts to embed not just the Advanced Alert view itself in them, but *any* view whose data the author owns (or if possible, whose data / image the author is entitled to export). The implementation would use the VIZ_IMAGE() placeholder text to do this, but allow passing in a path to the view in question, e.g.:

VIZ_IMAGE('myworkbook/myview')

This feature should also support customizing the view via [Filter values passed in via URL parameters](http://kb.tableau.com/articles/knowledgebase/view-filters-url), e.g.:

VIZ_IMAGE('myworkbook/myview?team=avengers')

Ideally, this would be built in such a way that we allowed it to be used for other content types as well (PDF, CSV), but those might need to be a new feature request.

**Comment by mcoles** [comment]
There's a temptation to want to allow Simple Alerts to do this too, but here's why that's a problem:

* If we were handed multiple customized paths for different rows of data, we wouldn't know what to do with it, since only one email could be sent if the alert were triggered.
* If a user subscribed to a Simple Alert that had a customized view path to a View they didn't have permission to access, they simply wouldn't be able to use the alert.
* It doesn't really keep Simple Alerts "simple". With the 0/1 flag, I think we're still achieving that.

**Comment by jdrummey** [comment]
This has now been implemented so this can be closed out.

**Comment by mcoles** [comment]
Many thanks, Mr. Drummey. Closing!
