### ISSUE TITLE
Trailing delimiters in recipients list cause "missing" error

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#61]
If you specify a delimited list of email addresses in the To field as follows:

larry@myorg.com;moe@myorg.com;curly@myorg.com;

...VizAlerts will throw a "Missing Email To *" failure email backatcha, because it's looking for the last email address in the list where it doesn't exist. We should be okay with empty addresses between delimiters so long as we at least have one valid address we've derived from the full string. Perhaps tokenize the string, iterate through the recips, then perform a check at the end for having parsed 0 valid emails out of it, returning an error in that case...

**Comment by AirCooledNut** [comment]
Agreed.  Extra delimiters _anywhere_ shouldn't matter in the to/from/CC fields.
