### ISSUE TITLE
Move documentation files to hosted HTML

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#79]
Currently, we have two documents that help admins and users understand how to install and use VizAlerts. They are both in Word (.docx) format. This is not idea for the following reasons:

- Can be more trouble to access (must download a file, rather than just viewing in browser)
- Must be opened in Word
- Links to documentation are somewhat awkward to send
- Changes are not tracked at a granular level and easily visualized

It might be worth looking into https://pages.github.com/ as a solution to this.

**Comment by jdrummey** [comment]
Me like, especially the part about tracking changes.

**Comment by stevenqzhang** [comment]
Here's a good example of markdown documentation: https://github.com/tableau/embedding-playbook

**Comment by stevenqzhang** [comment]
I used a online document converter and ended up with this: https://github.com/stevenqzhang/VizAlerts/blob/master/install_guide.md. I'd say it works well enough to convert to MD

**Comment by mcoles** [comment]
Yes, that looks like it will work well! Thanks Steven!

**Comment by mcoles** [comment]
This will be in 2.1.0
