### ISSUE TITLE
VIZ_LINK content reference doesn't work if placed after other content references

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#83]
The VIZ_LINK feature is working inconsistently in situations where multiple content references are being used. I'm not sure what the cause is just yet, but it appears to be on the replace function. The behavior I'm seeing is that when multiple content refs are used, the last VIZ_LINK ref just gets dumped into the email as raw text, e.g. "VIZ_LINK(workbook/view)", rather than replaced with the actual link.

If I test with two VIZ_LINK refs, one turns into a link and the other doesn't:

'VIZ_LINK(Test/Sheet1) VIZ_LINK(Test/Sheet2)'

...turns into the first link showing as raw text, and the second being turned into a link as expected. But reversing the order:

'VIZ_LINK(Test/Sheet2) VIZ_LINK(Test/Sheet3)'

...results in the first ref working properly, and the last being dumped in as raw text.

**Comment by jdrummey** [comment]
A quick guess here: we’ll need to check the regex code that finds the VIZ_LINK content references and makes the list/dictionary of them. I remember fixing bugs when first building the content reference code that the regex to find the content references would find the 1st reference but not the 2nd…Nth references and the symptom was exactly the behavior you describe where the Nth reference(s) would be passed through as raw text.

Also when it gets fixed we should add a test case for it to the tests.xlsx file.

**Comment by mcoles** [comment]
https://github.com/tableau/VizAlerts/blob/master/vizalert/vizalert.py#L1452

Lines 1452-1455 here need to be indented once, I think. They are only executed once, after all content references are looped over. Instead, this code should run at the end of each iteration, so that each content ref is replaced.

**Comment by jdrummey** [comment]
I think you identified the problem, I believe there would need to be two indents to place it in the elif block for the VIZ_LINK refs (see the prior section in 1412-1435 for VIZ_IMAGE for an example).

Jonathan

**Comment by mcoles** [comment]
Yep, that's right. I tested a fix and it seems to be working properly now.

**Comment by jdrummey** [comment]
Excellent, thanks!
