### ISSUE TITLE
Tableau server not pulling image in Map or in PDF downloads

### ISSUE THREAD

**Issue by lollyc** [tableau/VizAlerts#91]
I'm using tableau 10.0.2 and I have a map in one of my views. When I subscribe and receive an e-mail the map is showing up blank. When I click on the link to pull up the dashboard from the server, then I see the map. If i try to download a PDF of that dashboard from the server, again, the image of the map is blank.

Lastly, when I open the dashboard through the desktop and export the dashboard as an image, it then shows up.

Anyone have on issue with this?

Here's what it looks like when I download a pdf of the map from the Server:
http://i.imgur.com/DcqNbAz.png

Here's what it SHOULD look like and how It looks when I download through Tableau Desktop:
http://i.imgur.com/wZEuChL.png

**Comment by mcoles** [comment]
What was the issue?
