### ISSUE TITLE
Support a custom schedule representing "when the extract refreshes"

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#97]
We get a lot of folks wanting to schedule their alerts based on when the extract(s) in a workbook refresh. This seems do-able to implement as a VizAlerts feature. We could just pull the info from PostgreSQL into the config viz that describes when the last refresh operation completed. Additionally, we'd add some mechanism for the admin to define which (disabled) Subscription schedule would represent one of two conditions:

- On successful extract refresh
- On failed extract refresh

This could be a simple pattern-match calc, maybe the default could just be when the schedule name contains "extract" and "success" or "extract" and "fail".

Then, when VizAlerts runs, instead of using the schedule run_next_at date, it'd use the relevant extract refresh date(s) instead, for the workbook that was subscribed.

Trickiest part to think through here would be _which_ extracts we're talking about. Should we factor in published data sources? If so, I can see it being really hard to come up with the right date for which extract succeeded or failed. This is especially hard because the repo doesn't give us info on which connections in the workbook the view / sheet is actually using. And in the case of multiple published data sources referenced in a single workbook, each could have different schedules associated with its own extract refresh. That'd be totally confusing.

Okay, I think I just talked myself out of supporting published data sources. :) So it'd be just workbook-level extract refreshes.

**Comment by AirCooledNut** [comment]
LOL...Workbook level is fine.  Could you make it a function?  e.g. VAEXTRACT(_workbook_name_)  with an output of simply "Success" or "Fail"?

Or if you gotta have the choice option then VAEXTRACT(_workbook_name_, ["success"|"fail"]) where the second parameter specifies _what_ condition is being sought and the output is **True** or **False**. e.g. VAEXTRACT(_MyWorkbook_, "success") would return **True** if the extract was successful, otherwise it would return **False**.

**Comment by mcoles** [comment]
That's an interesting idea...I was thinking more on the Schedule side for my solution, so it'd be as easy as picking the Subscription Schedule named "VizAlerts - On Extract Refresh Success" or somesuch...that way the entire alert itself is conditional upon that event. Would you want to use a calc like that for formatting the output? Or for adding an additional condition to your alert?

**Comment by AirCooledNut** [comment]
Ah, I see what you were thinking.  I was thinking more of an additional condition for alerts but it could have other uses like for formatting.  Just throwing my 2 cents into the well :-)

**Comment by mcoles** [comment]
This will be in 2.1.0
